### ISSUE TITLE
Androidエミュレータでマイクが使えるか確認する

### ISSUE THREAD

**Issue by snakazawa** [swkoubou/peppermill-test#151]
マイクで声を5秒録音してその後スピーカーから音声を流す  
Android の manifest に注意。
# 要件
- 喋った声がAndroidエミュレータ上で再生される

**Comment by uryoya** [comment]
http://kazukii777.blogspot.jp/2013/05/android_5153.html

**Comment by uryoya** [comment]
https://developer.android.com/guide/topics/media/audio-capture.html
