### ISSUE TITLE
録音したファイルをwavに変換する

### ISSUE THREAD

**Issue by snakazawa** [swkoubou/peppermill-test#164]
録音しちゃってから [FFmpeg Android Java](http://writingminds.github.io/ffmpeg-android-java/) でやるのが楽かも。  
ライブラリなしだと結構コードを書く必要がある。  
クラス化してください。

マイクはここ参照: https://github.com/swkoubou/peppermill-test/tree/failure-run-record-app/record_test

**Comment by watayuz** [comment]
handlerの実装をしました（前に途中だったものに付け加えて実装しました）
確認のほど、宜しくお願いします

**Comment by snakazawa** [comment]
確認します

**Comment by snakazawa** [comment]
利用者が望むタイミングは変換が終わった時のはずです。
これだと意味がないですよね？

**Comment by snakazawa** [comment]
↑利用者がイベントを登録したいタイミング

**Comment by watayuz** [comment]
イベントの修正をしました。自分の理解が間違っているかもしれないですが、確認をお願いします

**Comment by snakazawa** [comment]
PRのほうでコメントするので少しまってください（ファイルが多すぎてよくわからない）
