### ISSUE TITLE
各アプリの整理

### ISSUE THREAD

**Issue by snakazawa** [swkoubou/peppermill-test#170]
リポジトリが整理されていないので、いらないものや検証コードはpeppermill-testにまとめる。  
必要なものや依存関係などは整理して、 "Pepper_Mill_timekeeper_android" リポジトリのreadmeに書き下す。  
リポジトリのプレフィックスは"peppermill"に統一しよう。  
- [本プロジェクトのリポジトリリスト](https://github.com/swkoubou?utf8=%E2%9C%93&query=pepper)
- [swkoubou/Pepper_Mill_timekeeper_android](https://github.com/swkoubou/Pepper_Mill_timekeeper_android)

**Comment by uryoya** [comment]
いらないものや検証コードの判別はファイル名から推測すればいいのですか？
あとJavaのプロジェクトなどの中にある検証コードをpeppermill-testに移動するときは、プロジェクトをまるごと持ってくるようにすればいいですか？

**Comment by snakazawa** [comment]
> いらないものや検証コードの判別はファイル名から推測すればいいのですか？

リポジトリ名やロジックあたりから推測してもらえれば。

> あとJavaのプロジェクトなどの中にある検証コードをpeppermill-testに移動するときは、プロジェクトをまるごと持ってくるようにすればいいですか？

それでOKです。適当な名前のディレクトリ名作って突っ込んでください。

**Comment by snakazawa** [comment]
最初に整理の計画立てて、一度ここに報告し確認してから行ってもらえると良いかと。

**Comment by uryoya** [comment]
了解しました

**Comment by uryoya** [comment]
[peppermill-heatupAPI](https://github.com/swkoubou/peppermill-heatupAPI): 何もしない
[peppermill-burst-ditector](https://github.com/swkoubou/peppermill-burst-ditector): 何もしない
[peppermill-wedding-atraction](https://github.com/swkoubou/peppermill-wedding-atraction): 何もしない
[peppermill-wedding-ringboy](https://github.com/swkoubou/peppermill-wedding-ringboy): 何もしない
[peppermill-timekeeper](https://github.com/swkoubou/peppermill-timekeeper): peppermill-testに移動
[peppermill-meetingsupport](https://github.com/swkoubou/peppermill-meetingsupport): peppermill-testに移動
[peppermill-heatup-post](https://github.com/swkoubou/peppermill-heatup-post): peppermill-testに移動

以上のようにしようと思いますが問題ないですか？

**Comment by snakazawa** [comment]
残るリポジトリ名と概要を列挙してもらえますか？
peppermill-test配下の検証プロジェクトの名前（ディレクトリ名）と概要も。
それらをpeppermill-testのREADME.mdに記したいです。

**Comment by uryoya** [comment]
残るリポジトリ
- peppermill-heatupAPI: heatup検知のためのAPI。burst-ditectorに依存
- peppermill-burst-ditector: 興奮検知の本体。heatupAPIに被依存
- peppermill-wedding-atraction: 結婚式の受付アプリ
- peppermill-wedding-ringboy: 結婚式のリングボーイアプリ

---

peppermill-testに移動するリポジトリ（ディレクトリ名は、リポジトリ名から"peppermill"を除いたものとする）
- peppermill-timekeeper: choregraphe時代のtimekeeperリポジトリ
- peppermill-meetingsupport: choregrapheとタブレットの通信テスト
- peppermill-heatup-post: Androidアプリ(Pepper)からheatupAPIを利用するテスト

---

簡易的かもしれないですがこのような説明になると思います

**Comment by snakazawa** [comment]
「残るリポジトリ」に、 `peppermill-timekeeper-android` を追加してください。
peppermill-test 配下のプロジェクトの記述には、既存のものも追加してもらえるとうれしいです。

**Comment by uryoya** [comment]
了解しました。
上に書いたものと、追加のものをREADMEに追記しておきます

**Comment by snakazawa** [comment]
お願いします。
いちお、branch切ってPRする感じで。

**Comment by uryoya** [comment]
一応確認なんですけどbranch切るのはpeppermill-testで大丈夫ですよね

**Comment by snakazawa** [comment]
はい。

**Comment by uryoya** [comment]
peppermill-timekeeperに関してですが、わかりやすくするためにディレクトリ名をtimekeeper-choregrapheにしました。
あと各リポジトリの.gitは削除したんですが、.gitignoreに関しても同様に削除して大丈夫ですか？

**Comment by snakazawa** [comment]
.gitignoreは階層的に適用されるので、残しておきましょう。

**Comment by snakazawa** [comment]
名前の適切な変更、ありがとうございます。

**Comment by uryoya** [comment]
.gitignore了解しました

**Comment by uryoya** [comment]
いま確認したところpeppermill-timekeeperにマージされてないブランチがあるんですがどうしますか？
現状ではmasterがpepermill-testに登録されています。（今更ですいません

**Comment by snakazawa** [comment]
確認します

**Comment by snakazawa** [comment]
古いのですね。無視でOKです。
https://github.com/swkoubou/peppermill-timekeeper/network

**Comment by uryoya** [comment]
了解しました。確認ありがとうございます

**Comment by uryoya** [comment]
https://github.com/swkoubou/peppermill-test/pull/176
リクエスト投げました。お願いします。
