### ISSUE TITLE
会議支援システムの動作部分を実装する

### ISSUE THREAD

**Issue by snakazawa** [swkoubou/peppermill-test#31]
- [x] Pepperが沈静化するときのアニメーションと発声
- [x] タイムオーバーしたときのアニメーションと発声
- [x] 残り時間をお知らせのアニメーションと発声

**Comment by watayuz** [comment]
現状Choregrapheで作成出来そうなところを挙げました。
会議支援システム
・会議スケジュール決める部分
・ボルテージ値が閾値を超えたらpepperが沈静化を始める部分
・Pepperが話す(沈静化する)ときのアニメーション作成
TimeKeeper アプリ
・タイムオーバーしたときの処理
・残り時間をお知らせの処理

作れなさそうなところや、他にも作れそうなところがあったらお願いします。

**Comment by snakazawa** [comment]
絶対にChoregrapheでやる部分である、以下をお願いします。

・Pepperが話す(沈静化する)ときのアニメーション作成
・タイムオーバーしたときの処理
・残り時間をお知らせの処理

アニメーションと、テキストも（適当でいいので）お願いします。

**Comment by watayuz** [comment]
了解しました

**Comment by watayuz** [comment]
とりあえずできる部分からで、

> ・Pepperが話す(沈静化する)ときのアニメーション作成
> ・タイムオーバーしたときの処理
> ・残り時間をお知らせの処理

の3つから実装を始めていきます。

**Comment by snakazawa** [comment]
このIssueのBodyにチェックボックスを作ったので、GitHubで開いて、完了したらチェックしてください。（KanbanはMarkdownに対応していません）

**Comment by watayuz** [comment]
適当に決めたメモリイベント名
PepperMill/TimeKeeper/TimeOver
PepperMill/TimeKeeper/TimeLeft
PepperMill/MeetingSupport/Calm

**Comment by snakazawa** [comment]
- [x] デフォルトポーズをStand状態に修正する。
